### ISSUE TITLE
exception.UnicodeEncodeError

### ISSUE THREAD

**Issue by jaimouest** [mpolednik/script.kodi.hue.ambilight#112]
Hi,
can you help me with this error : 

(PythonToCppException) : -->Python callback/script returned the following error<--                                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xe9' in position 5: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.kodi.hue.ambilight/default.py", line 313, in <module>
                                                hue = Hue(settings, args)
                                              File "/home/osmc/.kodi/addons/script.kodi.hue.ambilight/default.py", line 169, in __init__
                                                self.update_controllers()
                                              File "/home/osmc/.kodi/addons/script.kodi.hue.ambilight/default.py", line 227, in update_controllers
                                                self.static_controller,
                                              File "/home/osmc/.kodi/addons/script.kodi.hue.ambilight/resources/lib/lights.py", line 211, in __repr__
                                                return ('<{} {}>'.format(self.__class__.__name__, self.lights))
                                              File "/home/osmc/.kodi/addons/script.kodi.hue.ambilight/resources/lib/lights.py", line 96, in __repr__
                                                self.name, self.light_id, self.hue, self.sat, self.bri, self.on))
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 5: ordinal not in range(128)
                                            -->End of Python script error report<--
13:12:39.606 T:1695556352    INFO: Python script stopped

Thanks,

**Comment by jaimouest** [comment]
Ok, I found the problem: no accent in the name of Hue bulbs. So problem is solved or need to improve code ?
