### ISSUE TITLE
Can't find/detect Bridge

### ISSUE THREAD

**Issue by munkyplays** [mpolednik/script.kodi.hue.ambilight#56]
After installing requests and this masterbranch, restarting Kodi i can't find the Bridge.
Installed Kodi 17.1 on Windows 10 PC. Maybe there is a way to add Bridge manually?

**Comment by deusxm** [comment]
I have the exact same issue on Libreelec with Kodi 17.1 - log below:

`WARNING: RunScript called for a non-script addon 'script.kodi.hue.ambilight'. This behaviour is deprecated.
19:46:37.798 T:139833372559104 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
19:46:42.834 T:139832628594432   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
19:46:43.066 T:139833389344512 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
19:46:43.072 T:139832628594432   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.InvalidURL'>
                                            Error Contents: Invalid URL u'http:///api//lights': No host supplied
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.kodi.hue.ambilight/default.py", line 318, in <module>
                                                hue = Hue(settings, args)
                                              File "/storage/.kodi/addons/script.kodi.hue.ambilight/default.py", line 171, in __init__
                                                self.update_controllers()
                                              File "/storage/.kodi/addons/script.kodi.hue.ambilight/default.py", line 201, in update_controllers
                                                self.settings.ambilight_group.split(',')),
                                              File "/storage/.kodi/addons/script.kodi.hue.ambilight/resources/lib/bridge.py", line 66, in get_lights_by_ids
                                                req = requests.get('http://{}/api/{}/lights'.format(bridge_ip, username))
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 70, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 56, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 474, in request
                                                prep = self.prepare_request(req)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 407, in prepare_request
                                                hooks=merge_hooks(request.hooks, self.hooks),
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 302, in prepare
                                                self.prepare_url(url, params)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 369, in prepare_url
                                                raise InvalidURL("Invalid URL %r: No host supplied" % url)
                                            InvalidURL: Invalid URL u'http:///api//lights': No host supplied
                                            -->End of Python script error`

**Comment by munkyplays** [comment]
Something messed with the bridge in my case. Restarting the Bridge via unplugging the Power cable somehow fixed it for me.

**Comment by deusxm** [comment]
Tried this, no change.

**Comment by slydog3333** [comment]
I had this issue too as soon as I installed 17.1 over 17. It stopped connecting to the bridge at startup. I tried wiping settings and then it says it finds bridge at ip and to press button, when i press it does nothing. I was running on the script.kodi.hue.ambilight-1.0.zip version so I tried the new script.kodi.hue.ambilight-master.zip version(which is probably the same) with no effect.

**Comment by deusxm** [comment]
Just as a note on this, I downgraded my LibreELEC installation to 7.0.3 (uses Kodi 16.1) and then was able to detect my bridge straight away - even when using the v17 version of the script.

I then re-upgraded to LibreELEC 8.0.1 (Kodi 17.1) and the system works fine.

Evidently there is some sort of issue caused in Kodi 17+ for some installations.

**Comment by deusxm** [comment]
Ok, I got another bulb and tried to add it. Although it was detected by the add on, it didn't seem to control it. I tried resetting my settings and ended up back In the same place i.e. No bridge detection in Kodi 17. I tried my downgrade method and now that doesn't seem to work either. Any suggestions? Cheers!

**Comment by slydog3333** [comment]
Until there's an update on this addon, the only thing I can suggest is to use the cinemavision addon. I just setup a profile to use that just dims the lights and turns them back on on pause/stop to use until this is fixed. If you haven't used it before, you can also setup intro videos, previews and trivia to make it a whole movie theater experience. But it's kindof a pain atm since you have to go to the context menu to start it instead of just hitting play.

It was much better having the cinema vision option in the context menu while this addon took care of all the movies I didn't want to bother with the theater stuff.
