### ISSUE TITLE
Script crashes at Kodi startup

### ISSUE THREAD

**Issue by SailorMars** [mpolednik/script.kodi.hue.ambilight#98]
I am using an Intel NUC with LibreELEC (Krypton) 8.2.2 MR.
script.kodi.hue.ambilight is always crashing at startup but if I install the script after startup everything works like charm and all setting are stored.

I have disabled hardware acceleration but without any success.
It seems that LibreElec/Kodi is starting to quick so the script.kodi.hue.ambilight can't reach the hue bridge to establish the connection.

`18:20:31.173 T:140119080171264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: HTTPConnectionPool(host='192.168.3.56', port=80): Max retries exceeded with url: /api/lY9M-fpMr4jtqjvaKEVd52NEbCDoQK4viLTp-4K4/config (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6fd00603d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.kodi.hue.ambilight/default.py", line 313, in <module>
                                                hue = Hue(settings, args)
                                              File "/storage/.kodi/addons/script.kodi.hue.ambilight/default.py", line 165, in __init__
                                                self.settings.bridge_user
                                              File "/storage/.kodi/addons/script.kodi.hue.ambilight/resources/lib/bridge.py", line 15, in user_exists
                                                bridge_ip, bridge_user))
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 70, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 56, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 488, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 609, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 487, in send
                                                raise ConnectionError(e, request=request)
                                            ConnectionError: HTTPConnectionPool(host='192.168.3.56', port=80): Max retries exceeded with url: /api/lY9M-fpMr4jtqjvaKEVd52NEbCDoQK4viLTp-4K4/config (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f6fd00603d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
                                            -->End of Python script error report<--`

**Comment by keydon** [comment]
Try enabling `Add-ons` - `LibreElec Configuration` - `Network` - `Wait for network before starting Kodi`

**Comment by SailorMars** [comment]
Thanks that was the solution.
